### PR TITLE
Merge upstream/master

### PR DESCRIPTION
**Pull request by stvstnfrd**
## upstream/master:
- Make is possible to configure the database via environment vars.
- Use latest kombu==3.0.x
- Update openedx.yaml
- Add an OEP-2 compliant openedx.yaml file
- Fixed Image in discussion digest emails.
- better syntax
- adding DMS call to digest task
- Revert "adding calling to dms upon completion of digest task"
- adding calling to dms upon completion of digest task
- Language code fix

## Conflicts:
- AUTHORS
- notifier/tasks.py

### CODE REVIEW

**Comment by stvstnfrd** [comment]
Since we had to update forums, I figured we may as well bring notifier up-to-date too.

I went ahead and pulled from the most recent `upstream/master`, as there don't appear to be any incompatibilities :)

@kluo @caesar2164 Please review.

**Comment by caesar2164** [comment]
nice, if tests pass I'm 👍 

btw, that is a LOT of commits for that amount of changes...

**Comment by stvstnfrd** [comment]
> btw, that is a LOT of commits for that amount of changes...

Eh, this looks like a good thing. Each commit is focused :)

**Comment by stvstnfrd** [comment]
@kluo @caesar2164 Given how small this PR is, I'm wondering if we shouldn't just go ahead and merge it to master and release it to production. It appears to be backward compatible.

Thoughts?

**Comment by caesar2164** [comment]
No reason not to if it's clean. Makes merge and everything easier/simpler...

**Comment by stvstnfrd** [comment]
@kluo Ping.

**Pull request merged**
